---

driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: localhost
  require_ansible_repo: false
  ansible_verbose: true
  require_chef_for_busser: false
  require_ruby_for_busser: false

verifier:
  ruby_bindir: '/usr/bin'

platforms:
  - name: 'debian_8_x64'
    driver_config:
      box: 'abessifi/debian-jessie-ansible'
      network:
        - [ 'private_network', { ip: '192.168.33.111' } ]
  - name: 'centos_7_x64'
    driver_config:
      box: 'abessifi/centos-7.1-ansible'
      network:
        - [ 'private_network', { ip: '192.168.33.112' } ]

suites:
  - name: default
    attributes:
      tags:
        - install-java
  - name: override-java-version
    attributes:
      tags:
        - install-java
  - name: install-oracle-jdk
    attributes:
      tags:
        - install-java
