---

java:
  openjdk:
    debian_package: 'openjdk-8-jdk'
    redhat_package: 'java-1.8.0-openjdk'
    freebsd_package: 'openjdk'
  oracle:
    debian_package: 'oracle-java8-installer'

deb:
  debian:
    apt_backports_repo: 'deb http://http.debian.net/debian jessie-backports main'
  ubuntu:
    webupd8_key: 'EEA14886'
    webupd8_keyserver: 'keyserver.ubuntu.com'
    webupd8_repo: 'deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main'

rh:
  redhat:
    oracle_jdk_rpm_package: "{{ oracle_jdk_rpm_package | default('jdk-8u144-linux-x64.rpm') }}"
    oracle_jdk_rpm_url: "{{ oracle_jdk_rpm_url | default('http://download.oracle.com/otn-pub/java/jdk/8u144-b01/jdk-8u144-linux-x64.rpm') }}"
    oracle_jdk_download_cookie: 'gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'
    rpm_download_directory: "{{ rpm_download_directory | default('/var/cache/yum/x86_64/7/extras/packages') }}"

